export const GAME_SOUND_CONFIG = {
    basePath: 'gameassets/',
    commonSoundPath: "../common/",
    properties: {
        VOLUME: 1,
        MUTE: false,
        FADE_TIME: 1000,
    },
    pfsSoundFile: [
        // Gift FS
        { name: "VO_GiftFS", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
        { name: "VO_GiftBuyBonus", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
        { name: "sfxGiftBoxIntro", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
        { name: "sfxBoxAnticipation", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
        { name: "sfxBoxAnticipationV2", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
        { name: "VO_Congratulations", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
        { name: "sfxGiftBoxCongratulationsBanner", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
        { name: "sfxClick1", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
        { name: "sfxClick2", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
        { name: "sfxClick3", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
        { name: "sfxClick4", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
        { name: "sfxClick5", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
        { name: "sfxClick6", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
        { name: "sfxClick7", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
        { name: "sfxClick8", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
        { name: "sfxClick9", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
        { name: "sfxClick10", type: "common", loop: false, playEvents: [], volume: 1, fadeOutDuration: 0 },
    ],
    soundFiles: [

        { name: "sfxBetUp1", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 1, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp2", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 2, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp3", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 3, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp4", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 4, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp5", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 5, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp6", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 6, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp7", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 7, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp8", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 8, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp9", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 9, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp10", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 10, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp11", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 11, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp12", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 12, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp13", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 13, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp14", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 14, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp15", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 15, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp16", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 16, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp17", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 17, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp18", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 18, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp19", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 19, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp20", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 20, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp21", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 21, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp22", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 22, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp23", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 23, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp24", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 24, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp25", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 25, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp26", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 26, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp27", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 27, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp28", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 28, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp29", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 29, volume: 1, fadeOutDuration: 0 },
        { name: "sfxBetUp30", type: "common", loop: false, playEvents: ["PLAY_BET_SOUND"], matchParam: 30, volume: 1, fadeOutDuration: 0 },
        // { name: "sfxCelebration4", type: "game", loop: true, playEvents: ["START_MAINGAME_BG_MUSIC"], volume: 1 },
    ]
};
