export const BIG_WIN_CONFIG = {
    name: "bigwinComp", type: "Comp", class: "GameBigWinComp",
    Elements: [
        { name: "modalRect", type: "Graphics", width: 100, height: 100, color: 0x000000, alpha: 0 },
        {
            name: "winAmountComp", type: "Comp", class: "SlotWinAmountSequentialSpineCompV3", x: 0, y: 0, loopAfterEnd: false, dontAdd: true,
            textData: {
                "win": { fontSize: 100 },
            },
            bigAnimConfig: {
                defaultState: "big_idle",
                start: "big_intro",
                idleState: "big_idle",
                end: "big_intro",
                loop: true,
                scaleX: 1.2,
                scaleY: 1.2,
                scaleAnim: 1,
                scaleAnimP: 1,
                yAnimPaddingPerc: 0.55,
                yAnimPaddingPercP: 0.55,
                yPaddingPerc: 0.3,
                yPaddingPercP: 0.4,
                "bigWin": { fontSize: 100 },
            },
            megaAnimConfig: {
                defaultState: "mega_idle",
                start: "mega_intro",
                idleState: "mega_idle",
                end: "mega_intro",
                loop: true,
                scaleX: 1.2,
                scaleY: 1.2,
                scaleAnim: 1,
                yAnimPaddingPerc: 0.5,
                yAnimPaddingPercP: 0.52,
                yPaddingPerc: 0.3,
                yPaddingPercP: 0.4,
                "megaWin": { fontSize: 100 },
            },
            giganticAnimConfig: {
                defaultState: "gig_idle",
                start: "gig_intro",
                idleState: "gig_idle",
                end: "gig_intro",
                loop: true,
                scaleX: 1.2,
                scaleY: 1.2,
                scaleAnim: 1,
                yAnimPaddingPerc: 0.8,
                yAnimPaddingPercP: 0.4,
                yPaddingPerc: 0.3,
                yPaddingPercP: 0.52,
                "giganticWin": { fontSize: 100 },
            },
            unbelievableWinAnimConfig: {
                defaultState: "unb_idle",
                start: "unb_intro",
                idleState: "unb_idle",
                end: "unb_intro",
                loop: true,
                scaleX: 1,
                scaleY: 1,
                scaleAnim: 1,
                yAnimPaddingPerc: 0.3,
                yAnimPaddingPercP: 0.4,
                yPaddingPerc: 0.3,
                yPaddingPercP: 0.52,
                "unbelievableWin": { fontSize: 100 },
            },
            States: ["animation", "animation", "animation", "animation", "animation"],
            Elements: [
                { name: "guideRect", type: "Graphics", width: 1100, height: 730, color: 0xffff00, x: -13.5, y: 0, alpha: 1 },
                // { name: "coinAnim", type: "Spine", spineName: "coins2", defaultState: "", loop: true, scale: 0.7 },
                { name: "bigWinAnim", type: "Spine", spineName: "wins_body", defaultState: "", loop: true, yPaddingPerc: 0.4 },
                { name: "bigWins", type: "Spine", spineName: "wins_txt", defaultState: "", loop: true, yPaddingPerc: 0.4 },
                // { name: "bigwinbg", type: "Spine", spineName: "wins_panel", defaultState: "idle", loop: true, scale: {x: 0.5, y: 0.4}, x: 620, y: 518 },
                { name: "winText", type: "Comp", class: "LibAmountText", style: "winAmountStyle", anchor: { x: 0.5, y: 0.5 }, scale: 0.6, x: 550, y: 778 }
            ]
        },
    ],
}
